
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Class = 9;
  public static final int Coma = 44;
  public static final int Parentesis_Cerrado = 33;
  public static final int If = 17;
  public static final int Void = 12;
  public static final int sysCall = 15;
  public static final int Static = 11;
  public static final int Llave_Abierta = 34;
  public static final int Package = 4;
  public static final int Else = 18;
  public static final int Tipo_Dato = 3;
  public static final int Extends = 10;
  public static final int Operador_Logico = 27;
  public static final int Corchete_Cerrado = 37;
  public static final int Punto = 42;
  public static final int Operador_InDec = 30;
  public static final int While = 20;
  public static final int Division = 26;
  public static final int PuntoYcoma = 39;
  public static final int Parentesis_Abierto = 32;
  public static final int For = 21;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Operador_Atribucion = 29;
  public static final int Import = 5;
  public static final int Private = 7;
  public static final int Excepcion = 16;
  public static final int Do = 19;
  public static final int Catch = 14;
  public static final int Operador_Booleano = 31;
  public static final int Public = 6;
  public static final int Protected = 8;
  public static final int Corchete_Abierto = 36;
  public static final int Identificador = 40;
  public static final int Llave_Cerrada = 35;
  public static final int Try = 13;
  public static final int Resta = 24;
  public static final int Multiplicacion = 25;
  public static final int Numero = 41;
  public static final int Operador_Relacional = 28;
  public static final int Suma = 23;
  public static final int Main = 38;
  public static final int This = 43;
  public static final int Igual = 22;
  public static final int Comillas = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Comillas",
  "Tipo_Dato",
  "Package",
  "Import",
  "Public",
  "Private",
  "Protected",
  "Class",
  "Extends",
  "Static",
  "Void",
  "Try",
  "Catch",
  "sysCall",
  "Excepcion",
  "If",
  "Else",
  "Do",
  "While",
  "For",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Operador_Logico",
  "Operador_Relacional",
  "Operador_Atribucion",
  "Operador_InDec",
  "Operador_Booleano",
  "Parentesis_Abierto",
  "Parentesis_Cerrado",
  "Llave_Abierta",
  "Llave_Cerrada",
  "Corchete_Abierto",
  "Corchete_Cerrado",
  "Main",
  "PuntoYcoma",
  "Identificador",
  "Numero",
  "Punto",
  "This",
  "Coma"
  };
}

